[package]
name = "create-key"
version = "0.1.0"
authors = ["gregkapka <greg@oraclize.it>"]

[dependencies]
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1" }
rand = "0.4"
rustc-hex = "1.0"
ethereum-types = "0.4.0"
tiny-keccak = "1.4"
docopt = "1.0.1"
threadpool = "1.7.1"
