[package]
name = "create-key"
version = "0.1.0"
authors = ["gregkapka <greg@oraclize.it>"]

[dependencies]
ethkeygen = { path = "../" }

[[bin]]
name = "eth-keygen-rust"
path = "src/main.rs"
doc = false